"""empty message

Revision ID: a6cc9d2ec9e1
Revises: f73eab4df63e
Create Date: 2017-11-21 18:10:00.571452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6cc9d2ec9e1'
down_revision = 'f73eab4df63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'chapter', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chapter', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.drop_column(u'chapter', 'book_id')
    op.drop_table('book')
    # ### end Alembic commands ###
