"""empty message

Revision ID: bde38b4ce43b
Revises: 
Create Date: 2017-10-20 21:04:32.895805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bde38b4ce43b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_char',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('castmember_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['castmember_id'], ['castmember.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'event_ibfk_2', 'event', type_='foreignkey')
    op.drop_column(u'event', 'castmember_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'event', sa.Column('castmember_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'event_ibfk_2', 'event', 'castmember', ['castmember_id'], ['id'])
    op.drop_table('event_char')
    # ### end Alembic commands ###
