"""empty message

Revision ID: f73eab4df63e
Revises: a5aa2a3c47b8
Create Date: 2017-11-21 12:43:47.551061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73eab4df63e'
down_revision = 'a5aa2a3c47b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chapter', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.drop_column('chapter', 'user_id')
    # ### end Alembic commands ###
